// ─── Cache TTLs (seconds) ───
export const CACHE_TTL = {
  SCHEDULE: 600,
  STANDINGS: 300,
  WEATHER: 900,
  RACE_CONTROL: 15,
  INTERVALS: 10,
  POSITIONS: 10,
  DRIVERS: 300,
  STINTS: 15,
  RESULTS: 600,
  GRID: 600,
  LIVE_STATUS: 10,
} as const;

// ─── F1 Official Team Colours (2025) ───
export const TEAM_COLORS: Record<string, string> = {
  mclaren: "#FF8000",
  ferrari: "#E8002D",
  mercedes: "#27F4D2",
  red_bull: "#3671C6",
  aston_martin: "#229971",
  alpine: "#FF87BC",
  williams: "#64C4FF",
  rb: "#6692FF",
  sauber: "#52E252",
  haas: "#B6BABD",
};

// ─── Session Type Map ───
export const SESSION_TYPE_LABEL: Record<string, string> = {
  "Practice 1": "FP1",
  "Practice 2": "FP2",
  "Practice 3": "FP3",
  "Qualifying": "Q",
  "Sprint Qualifying": "SQ",
  "Sprint": "S",
  "Race": "R",
};

// ─── Race Flag Emoji Mapping ───
export const FLAG_CODE_MAP: Record<string, string> = {
  GBR: "gb",
  FRA: "fr",
  DEU: "de",
  ITA: "it",
  ESP: "es",
  NLD: "nl",
  BEL: "be",
  AUT: "at",
  HUN: "hu",
  CHE: "ch",
  AZE: "az",
  BHR: "bh",
  SAU: "sa",
  ARE: "ae",
  QAT: "qa",
  JPN: "jp",
  CHN: "cn",
  AUS: "au",
  USA: "us",
  MIA: "us",
  EMI: "us",
  CAN: "ca",
  MEX: "mx",
  BRA: "br",
  ARG: "ar",
  MON: "mc",
  MONaco: "mc",
  SGP: "sg",
  MYS: "my",
  KOR: "kr",
  IND: "in",
  VNM: "vn",
  ZAF: "za",
  RUS: "ru",
  TUR: "tr",
  POR: "pt",
  IRL: "ie",
  SWE: "se",
  NOR: "no",
  DNK: "dk",
  FIN: "fi",
  POL: "pl",
  CZE: "cz",
  ROU: "ro",
  BGR: "bg",
  HRV: "hr",
  SRB: "rs",
  UKR: "ua",
  LTU: "lt",
  LVA: "lv",
  EST: "ee",
  ISL: "is",
  LUX: "lu",
  MLT: "mt",
  AND: "ad",
  SMR: "sm",
  LIE: "li",
  BLR: "by",
  KAZ: "kz",
  UZB: "uz",
  GEO: "ge",
  ARM: "am",
  THA: "th",
  PAK: "pk",
  BGD: "bd",
  LKA: "lk",
  NPL: "np",
  MNG: "mn",
  TWN: "tw",
  HKG: "hk",
  PHI: "ph",
  IDN: "id",
  NZL: "nz",
  COL: "co",
  VEN: "ve",
  ECU: "ec",
  PER: "pe",
  CHL: "cl",
  URY: "uy",
  PRY: "py",
  BOL: "bo",
  CUB: "cu",
  JAM: "jm",
  TTO: "tt",
  GUY: "gy",
  SUR: "sr",
  CRI: "cr",
  PAN: "pa",
  HND: "hn",
  SLV: "sv",
  NIC: "ni",
  GTM: "gt",
  BLZ: "bz",
  DOM: "do",
  PRT: "pt",
  NGA: "ng",
  GHA: "gh",
  KEN: "ke",
  MAR: "ma",
  TUN: "tn",
  EGY: "eg",
  ETH: "et",
  TZA: "tz",
  ZMB: "zm",
  ZWE: "zw",
  MOZ: "mz",
  AGO: "ao",
  NAM: "na",
  BWA: "bw",
  MWI: "mw",
  MDG: "mg",
  MUS: "mu",
  SYC: "sc",
  COM: "km",
  BEN: "bj",
  CIV: "ci",
  SEN: "sn",
  MLI: "ml",
  BFA: "bf",
  NER: "ne",
  TCD: "td",
  CMR: "cm",
  GAB: "ga",
  CON: "cg",
  COD: "cd",
  GIN: "gn",
  GNB: "gw",
  SLE: "sl",
  LBR: "lr",
  RWA: "rw",
  BDI: "bi",
  UGA: "ug",
  SSD: "ss",
  ERI: "er",
  DJI: "dj",
  SOM: "so",
  SDN: "sd",
  LBY: "ly",
};
